#!/bin/bash
#
# add-flatpak-remote (afr)
#
# Add Flatpak remote(s) with sensible titles for display in GNOME Software

function add-flatpak-remote {
  for arg in "$@"; do
    case $arg in

      flathub | Flathub)
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        echo "Added Flathub user remote"
        ;;

      appcenter | AppCenter)
        flatpak remote-add --user --if-not-exists appcenter https://flatpak.elementary.io/repo.flatpakrepo
        echo "Added AppCenter user remote"
        ;;

      gnome-nightly | nightly)
        flatpak remote-add --user --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
        echo "Added GNOME Nightly user remote"
        ;;

      *)
        echo "Unknown Flatpak remote '$arg'"
        exit 1
        ;;
    esac
  done
}

alias afr='add-flatpak-remote'
