#!/bin/bash
#
# silverblue-misc (smisc)
#
# Miscellaneous commands I always use on Fedora Silverblue

function silverblue-misc {
  ## Add Flathub at a system level if it's not there
  flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak remote-modify --system flathub --no-filter --title="Flathub (System)" --description="Central repository of Flatpak applications"

  ## Add Flathub as a user remote
  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  ## Add GNOME Nightly as a user remote
  flatpak remote-add --user --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo

  ## Enable RPM Fusion (free and nonfree)
  # rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

  ## Uninstall apps to be replaced
  rpm-ostree override remove \
    firefox firefox-langpacks

  ## Install better defaults
  flatpak install --assumeyes --noninteractive --system flathub \
    org.gnome.Decibels \
    org.gnome.Epiphany \
    org.gnome.Loupe \
    org.gnome.Music \
    org.gnome.Papers \
    org.gnome.Showtime \
    org.gnome.Snapshot \
  ;

  ## My user apps
  flatpak install --assumeyes --noninteractive --user flathub \
    as.may.moat \
    com.bitwarden.desktop \
    com.cassidyjames.butler \
    com.cassidyjames.clairvoyant \
    com.cassidyjames.plausible \
    com.discordapp.Discord \
    com.github.cassidyjames.dippi \
    com.github.tchx84.Flatseal \
    com.mattjakeman.ExtensionManager \
    com.plexamp.Plexamp \
    com.prusa3d.PrusaSlicer \
    com.slack.Slack \
    com.ultimaker.cura \
    com.valvesoftware.Steam \
    de.haeckerfelix.Fragments \
    io.bassi.Amberol \
    me.dusansimic.DynamicWallpaper \
    net.hhoney.candy \
    net.hhoney.rota \
    net.hhoney.tinycrate \
    nl.hjdskes.gcolor3 \
    org.chromium.Chromium \
    org.gimp.GIMP \
    org.gnome.Boxes \
    org.gnome.Builder \
    org.gnome.design.Contrast \
    org.gnome.Fractal \
    org.godotengine.Godot \
    org.inkscape.Inkscape \
    org.mozilla.firefox \
    org.signal.Signal \
    re.sonny.Commit \
    tv.plex.PlexDesktop \
    tv.plex.PlexHTPC \
  ;
  flatpak install --assumeyes --noninteractive --user gnome-nightly \
    org.gnome.Adwaita1.Demo \
  ;
}

alias smisc='silverblue-misc'
